name: The Football Beat
favicon: null
layout_spectrum: 0.99707
typography_spectrum: 0.75293
title: The Football Beat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#303030'
    - '#fefefe'
    - '#6b6b6b'
    - '#c3c3c3'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
