name: The Football Beat
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9898D0'
    - '#181048'
    - '#A06060'
    - '#1838B8'
    - '#F0D870'
  brandStrength: 0
  lightness: 0.526182
  saturation: 0.514358
  rhythmicContrast: 0.5
purpose: []
