name: The Football Beat
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: The Football Beat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffdb'
    - '#0930bc'
    - '#4772e2'
    - '#d0b9e5'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
