analytics: {}
color:
  brandColors:
    - '#9898D0'
    - '#181048'
    - '#A06060'
    - '#1838B8'
    - '#F0D870'
  brandStrength: 1
  lightness: 0.526182
  rhythmicContrast: 1
  saturation: 0.514358
cta: {}
layout_spectrum: 0.50098
name: The Football Beat
opengraph: {}
purpose: []
typography_spectrum: 0
